package de.cimdata.hibernate;

// Generated 07.10.2013 11:17:36 by Hibernate Tools 4.0.0

/**
 * Friends generated by hbm2java
 */
public class Friends implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long friendshipId;
	private long userId;
	private long friendId;

	public Friends() {
	}

	public Friends(long userId, long friendId) {
		this.userId = userId;
		this.friendId = friendId;
	}

	public Long getFriendshipId() {
		return this.friendshipId;
	}

	public void setFriendshipId(Long friendshipId) {
		this.friendshipId = friendshipId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getFriendId() {
		return this.friendId;
	}

	public void setFriendId(long friendId) {
		this.friendId = friendId;
	}

}
