package de.cimdata.hibernate;

// Generated 07.10.2013 11:17:36 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Weights generated by hbm2java
 */
public class Weights implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long weightsId;
	private double weight;
	private Date date;
	private long userId;

	public Weights() {
	}

	public Weights(double weight, Date date, long userId) {
		this.weight = weight;
		this.date = date;
		this.userId = userId;
	}

	public Weights(Long userId) {
		this.userId = userId;
	}

	public Long getWeightsId() {
		return this.weightsId;
	}

	public void setWeightsId(Long weightsId) {
		this.weightsId = weightsId;
	}

	public double getWeight() {
		return this.weight;
	}

	public void setWeight(double weight) {
		this.weight = weight;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

}
