package hibernate;

// Generated 07.10.2013 11:17:36 by Hibernate Tools 4.0.0

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Long userId;
	private String username;
	private String password;
	private String firstname;
	private String lastname;
	private String email;
	private int yearbirth;
	private boolean sex;
	private double height;
	private Integer run;
	private Integer bike;
	private Integer swim;
	private Integer pump;
	private String status;
	private Integer fitnesslevel;

	public User() {
	}

	public User(String username, String password, String firstname,
			String lastname, String email, int yearbirth, boolean sex,
			double height) {
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.yearbirth = yearbirth;
		this.sex = sex;
		this.height = height;
	}

	public User(String username, String password, String firstname,
			String lastname, String email, int yearbirth, boolean sex,
			double height, Integer run, Integer bike, Integer swim,
			Integer pump, String status, Integer fitnesslevel) {
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.yearbirth = yearbirth;
		this.sex = sex;
		this.height = height;
		this.run = run;
		this.bike = bike;
		this.swim = swim;
		this.pump = pump;
		this.status = status;
		this.fitnesslevel = fitnesslevel;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getYearbirth() {
		return this.yearbirth;
	}

	public void setYearbirth(int yearbirth) {
		this.yearbirth = yearbirth;
	}

	public boolean isSex() {
		return this.sex;
	}

	public void setSex(boolean sex) {
		this.sex = sex;
	}

	public double getHeight() {
		return this.height;
	}

	public void setHeight(double height) {
		this.height = height;
	}

	public Integer getRun() {
		return this.run;
	}

	public void setRun(Integer run) {
		this.run = run;
	}

	public Integer getBike() {
		return this.bike;
	}

	public void setBike(Integer bike) {
		this.bike = bike;
	}

	public Integer getSwim() {
		return this.swim;
	}

	public void setSwim(Integer swim) {
		this.swim = swim;
	}

	public Integer getPump() {
		return this.pump;
	}

	public void setPump(Integer pump) {
		this.pump = pump;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getFitnesslevel() {
		return this.fitnesslevel;
	}

	public void setFitnesslevel(Integer fitnesslevel) {
		this.fitnesslevel = fitnesslevel;
	}

}
